version: '3.8'

services:
  AlumnosService:
    deploy:
      restart_policy:
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 500m
      update_config:
        parallelism: 1
        order: start-first
      labels:
        traefik.enable: "true"
    networks:
      - backend

networks:
  backend:
    external: true

