version: '3.8'

services:
  AlumnosService:
    image: $IMAGE_NAME
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.AlumnosService.rule: Host(`AlumnosService.apymsa-prdsvr.apymsa.com.mx`)
        traefik.http.routers.AlumnosService.entrypoints: http
        traefik.http.services.AlumnosService.loadbalancer.server.port: 80
